apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubernetes-kit-demo
spec:
  parentRefs:
    - name: public-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kubernetes-kit-demo-v1
          port: 80
          weight: 1
        - name: kubernetes-kit-demo-v2
          port: 80
          weight: 100
      sessionPersistence:
        sessionName: vaadin-session
        type: Cookie
